spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:${CONFIG_SERVER_URL:http://config-server:8888/}"
  
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 15
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000